server:
    port: 9001
    tomcat:
        connection-timeout: 2s
        keep-alive-timeout: 15s
        threads:
            max: 50
            min-spare: 5

springdoc:
    api-docs:
        path: /api-docs

#http://localhost:9001/swagger-ui/index.html

spring:
    application:
        name: catalog-service
    config:
        import: "optional:configserver:"
    cloud:
        config:
            uri: http://localhost:8888

polar:
    greeting: Welcome to the local book catalog!